"""Create Game Model

Revision ID: 846c33486c16
Revises: 0d06d41c7860
Create Date: 2022-12-29 22:52:57.226513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846c33486c16'
down_revision = '0d06d41c7860'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
